<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "courses".
 *
 * @property string $id
 * @property string $title
 * @property integer $price
 * @property string $content
 * @property string $image
 */
class Courses extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'courses';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'price', 'content', 'image'], 'required'],
            [['price'], 'integer'],
            [['title', 'content', 'image'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'price' => 'Price',
            'content' => 'Content',
            'image' => 'Image',
        ];
    }

    public function saveImage($filename)
    {
        $this->image = $filename;
        $this->save(false);
    }

    public function getImage()
    {
        return "/web/uploads/".$this->image;
    }

    public function deleteImage()
    {
        $del = new ImageUpload();
        $del->deleteCurrentImage($this->image);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
